Change logger and gps ldo to SPX3819M5-L-3-3, fix ltt nmos symbol
waterloo-rocketry/canhw pull request #56
Opened 2023-03-19 16:40 UTC by Rio6

LTT: fixed pinout of TSM2306
GPS, Logger: replaced LDO with known good SPX3819

2023-04-09 02:02 UTC, BluCodeGH approved these changes
GPS schematic part number changed, but part _value_ is still the MIC. Otherwise LGTM.

2023-04-13 22:18 UTC, JekkuChen requested changes
For both GPS and Logger, can the PDFs be updated to reflect the new LDO? Both of them still show the old MIC5504 LDO.

2023-04-14 19:31 UTC, JekkuChen approved these changes
LGTM

2023-04-15 20:12 UTC, eliaskountouris approved these changes

2023-04-15 22:16 UTC, merged