Add gecko 3D model
waterloo-rocketry/canhw pull request #69
Opened 2023-11-04 15:08 UTC by Joe-Joe-Joe-Joe

Add a 3D model for the new board-side gecko connectors

2023-11-04 15:21 UTC, Joe-Joe-Joe-Joe commented
Felt spicy so i added the SD card slot model too

2023-11-05 16:32 UTC, BluCodeGH requested changes
Sorry sir my name isn't joedo

![image](https://github.com/waterloo-rocketry/canhw/assets/22122986/8e5b8e40-90b9-43ef-9fdd-37bc966be8ec)

Please use paths relative to `${KIPRJMOD}/..`

2023-11-05 16:38 UTC, Joe-Joe-Joe-Joe commented
ahhhhhhhhhh
i thought it was smarter than that

2023-11-05 16:49 UTC, BluCodeGH approved these changes

2023-11-14 05:16 UTC, JasonBrave approved these changes

2023-11-26 02:57 UTC, DomenicHampson approved these changes

2023-11-26 03:07 UTC, merged