SRAD Altimeter
waterloo-rocketry/canhw pull request #91
Opened 2024-11-19 05:13 UTC by AshTheEngiqueer

Currently a schematic review only.

2025-01-05 15:47 UTC, KavinSatheeskumar commented
First round of comments, going to get food and will keep roasting

- Termination Resistor for GPS CAN Transceiver
- Talk to the GPS via Serial (or something else) rather than CAN, since having two independent CAN buses on one board has been a known pain point for Payload 2022
- can't look at the web-bench TI link because I cannot login
- Add no-connect to unconnected pin on the STM
- Looking at the TLP3543A here, (according to Ash), the direction of current of the two mosfets must be opposite, however there is nothing on the schematic to distinguish that. (IE, the little diodes inside the symbol both point in the same direction and the part numbers are the same)
![image](https://github.com/user-attachments/assets/9df3c751-8c0a-4f7c-b185-f86e949611c7)
- please add data sheet to all IC's used in your schematic

2025-01-05 16:09 UTC, KavinSatheeskumar commented
More comments

- This should be 3V3
![image](https://github.com/user-attachments/assets/1bb06996-4f08-4f9c-b0cf-b08000e1c286)
- Where do GPSCANH and GPSCANL
- This dosen't match the label coming into the sheet (from the outside its PYRO, on the inside its +PYRO)
![image](https://github.com/user-attachments/assets/1fd8889d-7006-4f64-83aa-a69b2a6eb0df)
- Connect to Ground 
![image](https://github.com/user-attachments/assets/e451b1c8-f74d-47ec-b49f-a21266cbba50)

2025-01-09 03:20 UTC, Armaan-Sengupta commented
1. Add another filter capacitor to 3v3 according to datasheet (same for the GPS one)
![image](https://github.com/user-attachments/assets/8c406bc6-5021-49f0-a017-96d00064f9aa) 
![image](https://github.com/user-attachments/assets/2c6f3f9d-844a-4ed7-bc06-4cfb687f875a)
2. VDD pin should be connected to 5V for GPS CAN
![image](https://github.com/user-attachments/assets/0c761976-d1c2-4cde-9bb3-d2459daeac02)
3. Enable should not be floating tie it to ground
![image](https://github.com/user-attachments/assets/d8e9ac80-7084-41d5-b3f3-20e60b414c2d)

Unfortunately i'll need to be given some context about how the pyros work before I can review those parts, but otherwise lgtm.

2025-01-09 03:22 UTC, Armaan-Sengupta requested changes
https://github.com/waterloo-rocketry/canhw/pull/91#issuecomment-2579103923

2025-01-09 17:05 UTC, AshTheEngiqueer commented
@Armaan-Sengupta 
1. sorry, wdym by another filter capacitor according to the datasheet? the image you've suggested says I need one on VDD and VIO?
2. I'm not convinced it should be, the GPS module takes 3V3 in so that's my justification behind running the altimeter/gps CAN on 3V3
3. datasheet says it doesnt matter

2025-01-09 20:56 UTC, Armaan-Sengupta commented
1. Yea to add a 0.1uF cap to VIO (3v3)
2. So the VIO should be 3V3 then right? But the actual MCP needs 5v (page 9) so VDD should be 5V
![image](https://github.com/user-attachments/assets/fa0ba24e-0439-4a9c-97e0-c80619de0478)
3. Ah yes I read the min max voltage backwards but I see the note on page 3 now. Also it has an internal pullup which I did not see before, yea chilling what u did makes sense.

2025-01-10 18:44 UTC, Rio6 commented
1. D1 is 1A max, is that enough? ![圖片](https://github.com/user-attachments/assets/00edd23d-c8c4-4720-bafc-834ee6344b85)
2. Is this huge capacitor neccessary? With LiPo instead of 9V I'd imagine it can source a lot more current on 12V side, and keeping 3V happy. 
![圖片](https://github.com/user-attachments/assets/4f9e49c5-0813-45df-92f0-e25ddb1bbe29)
4. These fuses can probably be bigger, what is the limiting factor here? 
![圖片](https://github.com/user-attachments/assets/31334e26-8048-439c-89b1-606db2d27e12)
5. 500ohm gives (3.3V - 1.8V) / 500 = 3mA which is just above the trigger current. The recommended forward current is 10mA from datasheet. 
![圖片](https://github.com/user-attachments/assets/fe4f6650-8bfc-49f1-a246-ed262de7510c)
6. Fix DRC (both errors and warnings), even if most of them are harmless they can bury actual errors

2025-01-10 20:10 UTC, AshTheEngiqueer commented
1. This was the diode sourced by Jason so idk, I'll look
2. Yup, good point, will think about this one more
3. Limiting factor is we'd like the fuse to break if the ematches are shorted (but this is kind of fake now that we have the 4R resistors I think? mag switch can take 20A for 5 seconds and 4R limits us to ~3A in case ematches are shorted)
4. Good catch, I forgot to account for the SSR forward voltage drop.
5. Not sure how to fix a bunch of the warnings? stuff like "input power pin not driven by output power pin", or "symbol pin or wire end off connection grid". those I've ignored, added NC symbols to all unused pins.

2025-01-10 20:20 UTC, Rio6 commented
For "wire end off grid" you can right click and ignore all that type of error.

For "power pin not driven" there's a power flag component you can connect to the power nets like this
![圖片](https://github.com/user-attachments/assets/a437f46f-6ea3-481b-a6a6-a021c0692a44)

2025-01-13 19:59 UTC, zx100x100 commented
1. pedantic, but I would recommend putting the current sensing math on the schematic so it is obvious the max current for each channel. I also don't love separating the shunt from the sensing amp on the schematic since it might be easier to forget that they need to be routed very close together.
![image](https://github.com/user-attachments/assets/2cd30dec-da58-43ba-9026-6ab51326f411)

2. What is your math for these pull-ups and sense circuits? what do you expect to see on the sense line across the different operating conditions? (IDK if it does what you want it to do)
![image](https://github.com/user-attachments/assets/d180e2b9-e1cf-4532-9170-8770564b06b6)

3. what is this supposed to do? it looks like current sensing, but the E-matches have a non-linear, variable resistance, so this doesn't work for current sensing since you don't know R
![image](https://github.com/user-attachments/assets/11cf2f05-3412-49d6-abf4-549849a5046e)

4. this part number is a 6 pin connector but the schematic is 2 pins! based on the spreadsheet 6 pins is correct, in which case I would recommend redundant connections for + and - so that we can harness parallel E-matches separately if desired.
![image](https://github.com/user-attachments/assets/009b03f6-cbaa-437f-ae05-5775938fa351)

5.As discussed documentation really needs updates, particularly to requirements, and description of system architecture

2025-01-21 04:43 UTC, BluCodeGH reviewed
1. Your labels for the programming pins are wrong. When only 2 pins are connecting we're using SWD not JTAG mode
2. Why do you have boot0 selection and a reset jumper? IIRC we've never used either, and camera worked just fine without either.
3. Why do you have an external oscillator? Again camera worked without it, the internal one is usually fine?
4. Resize the LED resistors for 3.3V
5. There are weird doubled up DNP resistors on the pololu sheet?
6. You don't need to connect to the pololu addr pin, save yourself the hassle and 1x1 connector.
7. Also you should inject 3.3V direct to VDD on the pololu not via VIN
8. It would be nice to use the 4R resistor as a pyro current sense measurement for real, probably via a voltage divider of the low side into the STM?
9. CANH/CANL test points are kinda silly cause there's a connector right there
10. I'd move the main/drogue testpoints to the pyro sheet
11. I'd also move the current sense testpoints to the power sheet
12. The INA4180 is kinda hard to lay out, I'd suggest 2x INA2180, one on the power sheet and one on the main sheet
13. The 5V LDO max input voltage is 12V, but lipos go to 12.6
14. The 3.3V buck has a soft start time of 2ms which isnt enough to charge the capacitor given its 3A limit, so we're going to be overcurrenting it. I really think you should reduce the requirements on that capacitor to make it a more reasonable size, eg maybe you only need 20ms and the STM32 can handle going to 2V or something, idk. Otherwise you need a buck with configurable soft start.
15. F1 has the wrong footprint, also are there smaller options? Its kinda big
16. L1 schematic value should be the part number, not the size
17. Same for C31
18. The ferrite bead is 0603, choose an 0805 one?
19. The SDMMC app note link is missing
20. I glanced at it but pls try to configure all your pins in STM32cube and make sure its happy before ordering
21. Like Zach mentioned you should change the pyro connectors, I think you should have a single M80 harwin with main + drogue in the same pinouy as RA.

2025-01-21 15:40 UTC, AshTheEngiqueer commented
@BluCodeGH 
2. Processor had both, I'll ask Joe if either was useful.
3. I know we use external oscillators for the PICs and processor also used an external oscillator. Didn't realize camera was fine without.
15. Not really? if we want a PTC with a hold current of 7.5A, max voltage >= 12.6V, and SMD then this is our only option. I suppose THT might be better, I'll do some looking

2025-03-05 16:27 UTC, BluCodeGH approved these changes
Schematic LGTM pending a few tweaks:
1.  Pyro connector pinout is wrong, we want main on pins 1/4 and drogue on pins 3/6
1. Typically you should put the current sense shunt resistors with the main circuit rather than near the INA, makes it clearer what's going on
1. Why do you have the pair of FETs that switch MAG_VOUT to +PYRO? The point of the pyro circuit is that it requires two actions to fire so there doesn't need to be any "armed" state. (Also those big FETs are really annoying to solder)
1. You should set the REF of the pyro op amp to 3.3/2 volts so you can sense current flowing in the opposite direction too right? (eg PY+ shorted to GND). You might need an analog input on the REF voltage too to be able to accurately determine the zero value, I'm not sure?
1. The gain of the pyro op amp might be too high? Assuming a single 1R pyro I get 6 mA through it (when we test by turning on the high side) which is 6V output at 1000V/V?

I didn't go through the full failure mode state analysis, do make sure it's up-to-date given the pyro current sensing you added and whatever opamp changes you make.

2025-03-05 17:14 UTC, AshTheEngiqueer commented
1. fixed
2. Zach and you have opposite opinions on this one - his argument is that the current sense resistor needs to be placed close to the INA
3. Yup, fair point. I was thinking about how RA worked and was wanting to build that functionality into this altimeter, but I see your point about how that doesnt make sense.
4. Do we care about being able to see if current is flowing backward with that op amp? If PY+ is shorted to some lower potential point (GND, for example), then SENSE_V will drop very close to GND as well.
5. Good catch

2025-05-13 04:04 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/86cec44b-0cf9-40a8-8608-177fb034ab9f)
make this label more descriptive. Was looking at the gnss breakout board and it's hard to tell what this means

2025-05-26 03:06 UTC, Joe-Joe-Joe-Joe commented
1. We have killed processor boards plugging rocketcan into the wrong gecko mistakenly. I wonder if there is a way to make this more idiot-proof
![image](https://github.com/user-attachments/assets/e4d1263c-0bff-4e09-aeb9-e69de975ef9f)
2. GPS datasheet? No way of knowing if this pinout is right
![image](https://github.com/user-attachments/assets/b88719da-19c0-4851-b612-21423e3a4501)
3. doesn't match Webench?
![image](https://github.com/user-attachments/assets/146cc88c-171f-40de-961a-12ee020359b9)

2025-05-28 16:38 UTC, StarlightDescender commented
1. Unfortunately no way to make this more idiotproof, if you plug powered rocketCAN into the GPS connector you're sending 12V somewhere.
2. Also this pinout is arbitrary, just has to match the breakout board and connect to the right pins of the 20-pin header.

2025-05-28 16:42 UTC, StarlightDescender commented
also oops thats embarrassing, the text link was correct but it hyperlinked to another converter

2025-06-08 21:44 UTC, Joe-Joe-Joe-Joe commented
1. Current limiting resistors on SSRs are skirting the minimum forward current requirement pretty close (about 6 mA vs 5 mA). For nominal forward voltage and current (1.64V 10 mA) you want ~166R. I dont know off the top of my head how much current the STM can sink/source. Is that related?
![image](https://github.com/user-attachments/assets/89d1ae10-b9a7-456a-b0aa-dcdd375e987e)
2. I question whether the power saving is worth using yet another different amp
![image](https://github.com/user-attachments/assets/f55a1119-3e17-4143-9060-f23ec787ac43)
3. I feel like this should be 0.1uF. Same with most other decoupling caps. We typically use 10uF only for decoupling the 2562s, I think because the CAN lines get switched so much. I'm no expert in why smaller caps are used, but I think it has smth to do with internal inductance?
![image](https://github.com/user-attachments/assets/336bff96-792a-4c96-88a0-cef5284dbf99)
4. Nit, but please exclude holes and (pad) TPs from the BOM e.g.
![image](https://github.com/user-attachments/assets/422dc165-d39e-44c5-b17c-46c975df31fa)


Layout
1. uhhhhh
![image](https://github.com/user-attachments/assets/ba81f367-97be-487e-9267-bd83dffb2173)
2. 
![image](https://github.com/user-attachments/assets/af00f008-c6b2-48bf-ab34-88ad1bd3a032)
![image](https://github.com/user-attachments/assets/5d080b4a-e0ea-4b49-96d0-0ae8a08b4d82)
3. Please clearly mark the clocking of the programmer on the silkscreen and ensure you have clearance to plug it it, given that clocking
![image](https://github.com/user-attachments/assets/8a6c5868-407b-4eeb-8851-876f824625c6)
4. Would be best to model the polulu in board CAD since it is a significant protrusion. Same w/ magswitch and battery connection
![image](https://github.com/user-attachments/assets/46da8e9b-332b-446b-8d5e-a660c8e49bab)
5. We talked about how this is designed to produce a unique voltage for each failure mode. Are those in a table somewhere? dont want telem doing MTE120 practice at the ops table figuring out whats failed
![image](https://github.com/user-attachments/assets/c8ff7ed5-d8aa-4eac-b2cc-c4bfe8fcc89c)
6. The heat sink plane for the power resistors is isolated. You cannot dissipate 35W continuously like that. What is the longest sustained power dissipation case here?
![image](https://github.com/user-attachments/assets/6521a13d-78b9-4bd6-b0d1-f3197b3a4d19)
7. Reminder to specify your part numbers if your parts come in different packages. I almost ordered the SSRs in a through-hole package
![image](https://github.com/user-attachments/assets/5ee9e9cb-f429-4b16-aebd-469c184a468e)
8. Zone border could use some cleanup, there is this random strip just on In1. Id just extend them all to board edge
![image](https://github.com/user-attachments/assets/f6ad7a60-df67-499d-a142-bda55c93f8b2)
9. Nit but name these GND/PWR
![image](https://github.com/user-attachments/assets/af403016-9c6b-4879-9449-62ec90085120)
10. TBH this Ihsan guy seems to know way more than I do about laying out power supplies I'm just gonna wait for him on that
11. Feel like this has clearance to clean up the layout a bit
![image](https://github.com/user-attachments/assets/6aec63ab-b17c-4884-a340-c75b836350b7)
12. TP 2 and 4 should have descriptions. For TPs I recommend moving the refdes off the board edge and then adding static text to describe it.
![image](https://github.com/user-attachments/assets/795945ee-0a90-4eaf-8c9b-3a75d0e2c7ce)

2025-06-09 16:50 UTC, ManavToor requested changes
Reviewing this on my lunch break at work lol, looks very good. Few small notes:
- you have a good amount of DRC errors and I think your mounting holes might be too close to the edge
- Inductor for buck converter is pretty close to a lot of the current sense stuff 
![image](https://github.com/user-attachments/assets/1787edbf-1e83-4a0a-9103-be013f9c1b98)
- Your grounds are not connected, this entire buck converter circuit is floating
![image](https://github.com/user-attachments/assets/8c021d6c-0a94-4d3b-9074-3178fa7c6dfd)

2025-06-09 18:06 UTC, StarlightDescender commented
- fixed mounting hole distances, the rest of DRC is fake (pads of a package too close together)
- yeah def not great , rotated the whole thing, have to run 3v3 trace underneath the inductor unfortunately but its probably fine?
- technically it was connected by a half via, fixed now though :)

2025-06-09 22:52 UTC, ManavToor approved these changes

2025-06-10 02:08 UTC, ihsan-sa approved these changes
LGTM

One thing I noticed: DRC is flagging a few incomplete thermal relief connections between planes and components. Should be fine because there's prob very little current, but just an FYI. In some places, you added an additional trace and via to the net.

Also, silkscreen is flagged for being too small in some places as per DRC, but that's not critical either.

Otherwise looks good! :)

2025-06-10 03:45 UTC, Lucifersan approved these changes
LGTM as well! No data/clock lines swapped and all that :heart_eyes:

2025-06-10 03:46 UTC, merged