Injector sensor hub
waterloo-rocketry/canhw pull request #92
Opened 2024-11-20 04:21 UTC by ecslewis

2025-03-15 20:13 UTC, Pdada1 requested changes
![image](https://github.com/user-attachments/assets/d9c652ca-d535-4aa6-a52c-2f5cee30a876)
With a 63 mR you only get span to 2.2V when you can go to 3.3 V on the input. You can use a 91mR instead to get more span to 3.18V and use more of the measurement range. 
![image](https://github.com/user-attachments/assets/22b675bc-7b86-428a-96c9-c809e7a649ce)
Label the frequency of your oscillator
![image](https://github.com/user-attachments/assets/0068e8d7-7f0d-48a9-bf4a-73469ccce70e)
Don't use global labels, use net labels instead here.

2025-03-29 21:57 UTC, Hexamech commented
1. Invalid datasheet link for buck converter
2. Minor but rename MC2562 to be MC**P**2562
3. Can connector and Programming header footprints seem to be in an uknown library for me

2025-04-16 03:29 UTC, Pdada1 reviewed
![image](https://github.com/user-attachments/assets/827ed8a5-b26a-4410-9dad-64138a113b6b)
I think your still making changes so I'm gonna wait go more thouroughly through the schematic, but something I noticed is that your connector is backwards. You wanna connect the wires to the round part (red arrow)

Might also be nice to list the sensors the board is being designed around in the analog sensor sheet. 
![image](https://github.com/user-attachments/assets/74c36e18-c4e8-4f73-ba39-1eda18dc3ffa)
Also your missing a voltage connection for this LED

2025-04-22 05:39 UTC, Pdada1 requested changes
K, like was me and ash were talking about, this board isn't actually running any sensor on 3V3 and every other component can run on 5V supplied from the can bus. So you can get rid of the LDO (SPX 3819) and shift everything to 5V. That'll mean you have resize the current sense resistors, as well as the current limiting resistors on the LEDs, as well as replace other connections
![image](https://github.com/user-attachments/assets/8baa809d-5ad2-4dbd-a3c1-ed0982175eb2)
voltage symbols should in general point up
Might be nice to list the sensors the board was designed for somewhere on the schematic

2025-04-27 17:14 UTC, StarlightDescender submitted a review, later dismissed
^ see above, and also please revert your changes to propulsion board + daq can support

2025-05-04 06:44 UTC, Pdada1 submitted a review, later dismissed
First off, I apologize for taking so long. 
![image](https://github.com/user-attachments/assets/ff5b5781-cba5-433b-80b1-cb97e41b9b85)
![image](https://github.com/user-attachments/assets/0548d1c9-b3d0-4a92-ad05-180142f81df8)
Your Can connector gecko is reversed. Remember to check the number each pin is wired to and not just the position since the connector symbol is the same when mirrored but each number corresponds to a different physical pin on the gecko. Second image is connector from rocket_power with right pin number connections
![image](https://github.com/user-attachments/assets/d9bdfb8a-3d97-46aa-b086-4c1ff39ce97d)
Now that the pic is running on 5V it's max adc voltage is also 5V so you should change the current sense resistor to take advantage of this additional range. at you can cahnge the 62mr to 130mR and get span to 4.5V instead of roughly 2V
![image](https://github.com/user-attachments/assets/8b3ceb82-23b3-4162-b4e5-73724fe9d7e6)
Nit but you can get rid fo this extra bend
![image](https://github.com/user-attachments/assets/799620b6-a8ff-4f0d-a35c-ba6e82c67bff)
Nit but you should connect these NC flags directly. The reason your having trouble placing them ontop of the pin is because your grid size has changed at some point. 
![image](https://github.com/user-attachments/assets/583cbbe8-eb2d-4dcd-8867-60893c316c9a)
If you change it to one size down by right click menu, you'll be able to place them directly
Otherwise LGTM
@StarlightDescender @JasonBrave 
do we have the can harness assignment documented somewhere, or maybe we can throw it in electrical standards. It seems really jank to have to open existing boards in order to check against

2025-05-04 18:13 UTC, StarlightDescender commented
We do have CAN harness pinout, but it's out of date 💀 to be updated Soon (tm)

2025-05-13 04:20 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/64a8decb-abcf-4c1e-9770-6a480bc6f3da)
please point ground downwards otherwise LGTM

2025-05-16 14:06 UTC, Joe-Joe-Joe-Joe commented
1. You should only have one KiCAD project file. You seem to have 3 plus another nested project. Delete the excess ones please
![image](https://github.com/user-attachments/assets/52da6ede-ecee-4f8f-9fe1-e5f873a93e7f)
2. Your hierarchical labels are not consistent. You have 6 on the MCU, 8 going into the MCU sheet, and only 6 coming out of the sensors sheet (which themselves are duplicates)
![image](https://github.com/user-attachments/assets/1dbd8b8a-bd46-45e4-83b7-a70d180422e3)
![image](https://github.com/user-attachments/assets/33fa79ac-024b-4fa8-ad5c-9dd05f8d79c4)
![image](https://github.com/user-attachments/assets/6afaaa76-a3ed-4de6-8b35-3036e01b84b1)
3. We normally stock red, green, and blue (and white) LEDs. Is there a particular reason this needs a yellow one?
![image](https://github.com/user-attachments/assets/4faac1c1-1a12-4027-9db1-402daf95f60e)

2025-05-18 14:59 UTC, ManavToor commented
Please address Joe's comments and also begin working on the layout

2025-05-27 21:41 UTC, StarlightDescender approved these changes

2025-05-27 23:35 UTC, Lucifersan commented
Given the nit that ash did I would also say another nit is while you're doing that, please move the LEDs (and their respective resistors) a bit further from each other, they're really close right now. We're not tight on space so there's no reason to cram them like that imo

2025-05-27 23:39 UTC, Lucifersan commented
<img width="255" alt="Screenshot 2025-05-27 at 7 36 01 PM" src="https://github.com/user-attachments/assets/c871859c-15eb-405b-b910-c233e632270f" />
In a similar vein, another nit: I think these connectors are both 1) _really_ close together for no reason because theres space to move them apart and 2) not evenly spaced which is a bit :(

2025-05-27 23:42 UTC, Lucifersan approved these changes
I will not block on any of these nits because of the time pressure, but I do think they should be changed regardless

2025-05-28 17:32 UTC, Lucifersan commented
^ seconded lol

2025-05-28 17:51 UTC, Lucifersan approved these changes
lgtm :D

2025-05-28 17:55 UTC, StarlightDescender approved these changes
send it

2025-05-29 19:45 UTC, Pdada1 reviewed
![image](https://github.com/user-attachments/assets/d321aaf3-fd53-4ac1-a0dc-4c7c532858a5)
nit we have daisy chaining here
![image](https://github.com/user-attachments/assets/9a0f9dc9-6159-46c9-a0a2-424534e4b53f)
 nit you can make this trace smaller by assigning this to pin 15 instead
![image](https://github.com/user-attachments/assets/1e125140-1170-4e14-88d5-f1716902f891)
trace can be eliminated
![image](https://github.com/user-attachments/assets/2a27ab4c-1d1b-4a13-8256-8be4e4c823ed)
think it's kinda sus to have the 5V islands be bridged by the pic 5V pin, and also have that super in area on the pour
![image](https://github.com/user-attachments/assets/3b988c46-9a1e-4782-b5ae-f56e306bc27c)
there is a lot of bplane area here to put in some stictching

2025-05-30 03:02 UTC, Pdada1 commented
> nit but board name should be "sensor? I hardly know 'er!" rather than charger. otherwise LGTM

I honestly don't know how much the first years care, but I think they should be able to choose the name for the board. How else are they supposed to establish a series

2025-05-30 03:27 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/a72b58d8-a669-4196-bd29-389af0b582d6)
We want the both planes of the oscillator to be isolated right?

2025-05-31 17:35 UTC, Joe-Joe-Joe-Joe approved these changes
LGTM

2025-05-31 17:35 UTC, merged